"""Frozen V-JEPA 2 encoder, wrapping HuggingFace `transformers.VJEPA2Model`.

API verified against the installed `transformers` source
(`transformers/models/vjepa2/{modeling,configuration,video_processing}_vjepa2.py`)
rather than guessed:

  * `VJEPA2Model.forward` / `get_vision_features` expects
    `pixel_values_videos` of shape (batch, num_frames, channels, H, W)
    (see `VJEPA2Embeddings.forward`, which reads `shape[1]` as the frame
    axis and permutes to (B, C, T, H, W) before the Conv3d patch embed).
  * `get_vision_features` returns the encoder's `last_hidden_state` of
    shape (batch, num_patches, hidden_size) -- a token per
    (tubelet_size, patch_size, patch_size) spatio-temporal patch -- with
    no built-in pooling, which is why this module mean-pools over tokens
    itself (project principle: prefer the simplest pooling before
    anything fancier).
  * The reference preprocessing (`VJEPA2VideoProcessor`) resizes so the
    shortest edge is `crop_size * 256 / 224`, center-crops to
    `crop_size`, and normalizes with ImageNet mean/std. We reimplement
    that by hand with numpy/PIL instead of calling
    `AutoVideoProcessor.from_pretrained(...)`, because that call needs
    network access to Hugging Face Hub, which is unavailable in some
    environments (including the one this repo was first built in) even
    when the checkpoint itself is available locally.

IMPORTANT -- pretrained weights: `from_pretrained` downloads weights from
Hugging Face Hub, which requires outbound network access to
huggingface.co. Some sandboxed environments block that host. When it is
unreachable, this class falls back to a randomly-initialized model with
the same architecture (config only, no learned weights) and *loudly
prints/logs a warning* -- see `pretrained=False` and DESIGN.md
"Encoder: honesty about pretrained weights". Results produced with
`pretrained=False` validate the *pipeline*, not any claim about what
V-JEPA 2 actually represents, and every report generated by this repo
must say which mode was used.
"""

from __future__ import annotations

import logging
import warnings

import numpy as np

from encoders.base import FrozenEncoder

logger = logging.getLogger(__name__)

IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMAGENET_STD = np.array([0.229, 0.224, 0.225], dtype=np.float32)

# ViT-L/16 architecture constants (facebook/vjepa2-vitl-fpc64-256's actual
# config.json, verified via live Hub access -- see encoders/vjepa.py's
# module docstring: the ViT-B V-JEPA 2 checkpoint this file originally
# assumed does not exist on the Hub under any namespace; ViT-L is the
# smallest official facebook/-namespaced V-JEPA 2 checkpoint). Used for
# the from_pretrained=False fallback so the untrained model at least
# matches the intended model size.
VITL16_CONFIG_KWARGS = dict(
    patch_size=16,
    hidden_size=1024,
    num_attention_heads=16,
    num_hidden_layers=24,
    pred_hidden_size=384,
    pred_num_attention_heads=12,
    pred_num_hidden_layers=12,
)

DEFAULT_CHECKPOINT = "facebook/vjepa2-vitl-fpc64-256"


class VJEPA2Encoder(FrozenEncoder):
    def __init__(
        self,
        checkpoint: str = DEFAULT_CHECKPOINT,
        pretrained: bool = True,
        crop_size: int = 128,
        frames_per_clip: int = 8,
        tubelet_size: int = 2,
        device: str = "cpu",
    ):
        import torch
        from transformers import VJEPA2Config, VJEPA2Model

        self.torch = torch
        self.device = device
        self.crop_size = crop_size
        self.resize_size = int(round(crop_size * 256 / 224))
        self.pretrained = pretrained
        self.checkpoint = checkpoint

        if pretrained:
            try:
                self.model = VJEPA2Model.from_pretrained(checkpoint)
            except Exception as exc:  # network/hub failure, missing checkpoint, etc.
                warnings.warn(
                    f"Could not load pretrained checkpoint '{checkpoint}' ({exc!r}). "
                    "Falling back to a randomly-initialized VJEPA2 model with the same "
                    "architecture. Results are for PIPELINE VALIDATION ONLY and must not "
                    "be interpreted as saying anything about V-JEPA 2's real representations. "
                    "See encoders/vjepa2.py and DESIGN.md.",
                    RuntimeWarning,
                    stacklevel=2,
                )
                logger.warning("Falling back to untrained VJEPA2 (pretrained load failed): %s", exc)
                self.pretrained = False
                config = VJEPA2Config(
                    crop_size=crop_size,
                    frames_per_clip=frames_per_clip,
                    tubelet_size=tubelet_size,
                    **VITL16_CONFIG_KWARGS,
                )
                self.model = VJEPA2Model(config)
        else:
            config = VJEPA2Config(
                crop_size=crop_size,
                frames_per_clip=frames_per_clip,
                tubelet_size=tubelet_size,
                **VITL16_CONFIG_KWARGS,
            )
            self.model = VJEPA2Model(config)

        self.model.eval().to(device)
        for p in self.model.parameters():
            p.requires_grad_(False)

        self.output_dim = self.model.config.hidden_size

    def _preprocess(self, frames: np.ndarray) -> "torch.Tensor":
        """frames: (T, H, W, 3) uint8 -> (1, T, 3, crop, crop) normalized float tensor."""
        import torch
        import torch.nn.functional as F

        t = torch.from_numpy(frames).float() / 255.0  # (T, H, W, 3)
        t = t.permute(0, 3, 1, 2)  # (T, 3, H, W)
        t = F.interpolate(t, size=(self.resize_size, self.resize_size), mode="bilinear", align_corners=False)
        offset = (self.resize_size - self.crop_size) // 2
        t = t[:, :, offset:offset + self.crop_size, offset:offset + self.crop_size]
        mean = torch.tensor(IMAGENET_MEAN).view(1, 3, 1, 1)
        std = torch.tensor(IMAGENET_STD).view(1, 3, 1, 1)
        t = (t - mean) / std
        return t.unsqueeze(0)  # (1, T, 3, crop, crop)

    def encode_video(self, frames: np.ndarray) -> np.ndarray:
        pixel_values = self._preprocess(frames).to(self.device)
        with self.torch.no_grad():
            tokens = self.model.get_vision_features(pixel_values)  # (1, num_patches, hidden)
            pooled = tokens.mean(dim=1).squeeze(0)  # simple mean pooling over tokens
        return pooled.cpu().numpy().astype(np.float32)
